USE BINAES;
GO
DELETE FROM USER_
SELECT * FROM USER_;
SELECT * FROM COLLECTION_;
SELECT * FROM TYPE_;
SELECT * FROM GENRE;
SELECT * FROM CELEBRATION
SELECT * FROM OCCUPANCY;
SELECT * FROM ROLE_;
SELECT * FROM INSTITUTION;
USE master;