--CREACION DE CONEXIONES CON FK
ALTER TABLE COLECCION ADD CONSTRAINT fk_genero_coleccion
	FOREIGN KEY(id_genero) REFERENCES GENERO(id);
GO    
ALTER TABLE COLECCION ADD CONSTRAINT fk_tipo_coleccion
	FOREIGN KEY(id_tipo) REFERENCES TIPO(id);
GO
ALTER TABLE ETIQUETA ADD CONSTRAINT fk_etiqueta_ejemplar
	FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
GO
ALTER TABLE LISTA_PALABRAS ADD CONSTRAINT fk_ejemplar_lista
	FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
GO
ALTER TABLE AUTOR ADD CONSTRAINT fk_ejemplar_autor
	FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
GO
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_coleccion
	FOREIGN KEY(id_coleccion) REFERENCES COLECCION(id);
GO
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_idioma
	FOREIGN KEY(id_idioma) REFERENCES IDIOMA(id);
GO
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_formato
	FOREIGN KEY(id_formato) REFERENCES FORMATO(id);
GO
ALTER TABLE USUARIO ADD CONSTRAINT fk_institucion
	FOREIGN KEY(id_institucion) REFERENCES INSTITUCION(id);
GO
ALTER TABLE USUARIO ADD CONSTRAINT fk_ocupacion
	FOREIGN KEY(id_ocupacion) REFERENCES OCUPACION(id);
GO
ALTER TABLE AREA ADD CONSTRAINT fk_responsable
	FOREIGN KEY(id_responsable) REFERENCES RESPONSABLE(id)
GO
ALTER TABLE OBJETIVO ADD CONSTRAINT fk_evento
	FOREIGN KEY(id_evento) REFERENCES EVENTO(id)
GO
ALTER TABLE EVENTO ADD CONSTRAINT fk_area
	FOREIGN KEY(id_area) REFERENCES AREA(id);
GO
--TABLAS CRUZ
ALTER TABLE PRESTAMO_RESERVA ADD 
    CONSTRAINT pk_prestamo_reserva
        PRIMARY KEY(id_usuario, id_ejemplar),
    CONSTRAINT fk_usuario_prestamo_reserva
        FOREIGN KEY (id_usuario)
        REFERENCES USUARIO(id),
    CONSTRAINT fk_ejemplar_prestamo_reserva
        FOREIGN KEY (id_ejemplar)
        REFERENCES EJEMPLAR(id);
GO
ALTER TABLE ASISTENCIA ADD 
    CONSTRAINT pk_asistencia
        PRIMARY KEY(id_area, id_usuario),
    CONSTRAINT fk_area_asistencia
        FOREIGN KEY (id_area)
        REFERENCES AREA(id),
    CONSTRAINT fk_usuario_asistencia
        FOREIGN KEY (id_usuario)
        REFERENCES USUARIO(id);