--SELECCION DE BASE DE DATOS
USE BINAES;

--CREACION DE CONEXIONES CON FK
--TABLA COLECCION
ALTER TABLE COLECCION ADD CONSTRAINT fk_genero_coleccion
	FOREIGN KEY(id_genero) REFERENCES GENERO(id);
GO    
ALTER TABLE COLECCION ADD CONSTRAINT fk_tipo_coleccion
	FOREIGN KEY(id_tipo) REFERENCES TIPO(id);
GO
--TABLA ETIQUETA
ALTER TABLE ETIQUETA ADD CONSTRAINT fk_ejemplar_etiqueta
	FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
GO
--TABLA LISTA DE PALABRAS
ALTER TABLE LISTA_PALABRAS ADD CONSTRAINT fk_ejemplar_lista
	FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
GO
--TABLA AUTOR
ALTER TABLE AUTOR ADD CONSTRAINT fk_ejemplar_autor
	FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
GO
--TABLA EJEMPLAR
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_coleccion_ejemplar
	FOREIGN KEY(id_coleccion) REFERENCES COLECCION(id);
GO
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_idioma_ejemplar
	FOREIGN KEY(id_idioma) REFERENCES IDIOMA(id);
GO
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_formato_ejemplar
	FOREIGN KEY(id_formato) REFERENCES FORMATO(id);
GO
--TABLA USUARIO
ALTER TABLE USUARIO ADD CONSTRAINT fk_institucion_usuario
	FOREIGN KEY(id_institucion) REFERENCES INSTITUCION(id);
GO
ALTER TABLE USUARIO ADD CONSTRAINT fk_ocupacion_usuario
	FOREIGN KEY(id_ocupacion) REFERENCES OCUPACION(id);
GO
--TABLA AREA
ALTER TABLE AREA ADD CONSTRAINT fk_responsable_area
	FOREIGN KEY(id_responsable) REFERENCES RESPONSABLE(id)
GO
--TABLA OBJETIVO
ALTER TABLE OBJETIVO ADD CONSTRAINT fk_evento_objetivo
	FOREIGN KEY(id_evento) REFERENCES EVENTO(id)
GO
--TABLA EVENTO
ALTER TABLE EVENTO ADD CONSTRAINT fk_area_evento
	FOREIGN KEY(id_area) REFERENCES AREA(id);
GO
--TABLAS CRUZ
--TABLA PRESTAMO_RESERVA
ALTER TABLE PRESTAMO_RESERVA ADD CONSTRAINT fk_usuario_pxr
    FOREIGN KEY(id_usuario) REFERENCES USUARIO(id);
GO
ALTER TABLE PRESTAMO_RESERVA ADD CONSTRAINT fk_ejemplar_pxr
    FOREIGN KEY(id_ejemplar) REFERENCES EJEMPLAR(id);
GO
--TABLA ACTIVIDAD
ALTER TABLE ACTIVIDAD ADD CONSTRAINT fk_area_actividad
    FOREIGN KEY(id_area) REFERENCES AREA(id);
GO
ALTER TABLE ACTIVIDAD ADD CONSTRAINT fk_evento_actividad
    FOREIGN KEY(id_evento) REFERENCES EVENTO(id);
GO 
ALTER TABLE ACTIVIDAD ADD CONSTRAINT fk_asistencia_actividad
    FOREIGN KEY(id_asistencia) REFERENCES ASISTENCIA(id);
GO 
--TABLA ASISTENCIA
ALTER TABLE ASISTENCIA ADD CONSTRAINT fk_actividad_asistencia
    FOREIGN KEY(id_actividad) REFERENCES ACTIVIDAD(id);
GO
ALTER TABLE ASISTENCIA ADD CONSTRAINT fk_usuario_asistencia
    FOREIGN KEY(id_usuario) REFERENCES USUARIO(id);
GO